export const runtime = 'nodejs'
export const dynamic = 'force-dynamic'
export const maxDuration = 300

import { NextResponse } from 'next/server'
import { verifyCronAuth } from '@/lib/auth/cron'
import { supabaseAdmin } from '@/lib/supabase-admin'
import { BasAgent, getCurrentQuarter } from '@/lib/agents/bas-agent'

export async function GET(req: Request) {
  const denied = verifyCronAuth(req)
  if (denied) return denied

  const { data: businesses } = await supabaseAdmin
    .from('businesses')
    .select('id')
    .eq('is_active', true)

  const q = getCurrentQuarter()
  const now = new Date()
  const daysUntilPeriodEnd = (q.period_end.getTime() - now.getTime()) / 86400000
  const daysUntilDue = (q.due_date.getTime() - now.getTime()) / 86400000

  const agent = new BasAgent()
  let autoGenerated = 0

  for (const biz of businesses ?? []) {
    try {
      // Check if draft exists for current quarter
      const { data: existing } = await supabaseAdmin
        .from('bas_drafts')
        .select('id,status,due_date')
        .eq('business_id', biz.id)
        .eq('period_start', q.period_start.toISOString().slice(0, 10))
        .maybeSingle()

      // Auto-generate if 30 days from quarter end and no draft
      if (!existing && daysUntilPeriodEnd <= 30) {
        await agent.generateBasDraft(biz.id, q.period_start, q.period_end)
        autoGenerated++
      }

      // 14-day reminder for unlodged BAS
      if (existing && existing.status !== 'lodged' && daysUntilDue <= 14 && daysUntilDue > 0) {
        try {
          await supabaseAdmin.from('aria_autopilot_actions').insert({
            business_id: biz.id,
            category: 'compliance',
            action_type: 'bas_reminder',
            title: 'BAS due in ' + Math.round(daysUntilDue) + ' days',
            description: 'BAS due in ' + Math.round(daysUntilDue) + ' days (' + q.due_date.toISOString().slice(0, 10) + '). Status: ' + existing.status + '. Log in to review.',
            status: 'pending',
          })
        } catch (e) { console.error('[non-fatal]', e) }
      }

      // Super payment alerts
      const { data: unpaidSuper } = await supabaseAdmin
        .from('super_obligations')
        .select('id,staff_name,super_amount_owed,payment_due_date')
        .eq('business_id', biz.id)
        .neq('status', 'paid')
        .not('payment_due_date', 'is', null)

      for (const superRow of unpaidSuper ?? []) {
        if (!superRow.payment_due_date) continue
        const daysUntilSuperDue = (new Date(superRow.payment_due_date).getTime() - now.getTime()) / 86400000
        if (daysUntilSuperDue <= 14 && daysUntilSuperDue > 0) {
          try {
            await supabaseAdmin.from('aria_autopilot_actions').insert({
              business_id: biz.id,
              category: 'compliance',
              action_type: 'super_reminder',
              title: 'Super payment due in ' + Math.round(daysUntilSuperDue) + ' days',
              description: 'Super payment due in ' + Math.round(daysUntilSuperDue) + ' days for ' + superRow.staff_name + ': $' + Number(superRow.super_amount_owed).toFixed(0),
              status: 'pending',
            })
          } catch (e) { console.error('[non-fatal]', e) }
        }
      }
    } catch { /* per-biz errors non-fatal */ }
  }

  return NextResponse.json({ ok: true, auto_generated: autoGenerated, businesses: businesses?.length ?? 0 })
}
