export const POS_PERMISSIONS = {
  // Sales
  can_process_sale: true,
  can_apply_discount: false,
  can_apply_discount_over_10pct: false,
  can_void_item: false,
  can_void_sale: false,
  can_process_refund: false,
  can_override_price: false,
  can_add_notes_to_sale: true,
  // Cash
  can_open_cash_drawer: true,
  can_view_cash_session: false,
  can_close_cash_session: false,
  can_view_float: false,
  // Customers
  can_view_customers: true,
  can_add_customer: true,
  can_edit_customer: false,
  can_redeem_loyalty: true,
  // Inventory
  can_view_stock: true,
  can_adjust_stock: false,
  can_receive_order: false,
  // Staff
  can_view_roster: true,
  can_clock_in_out: true,
  can_view_other_timesheets: false,
  // Reports
  can_view_daily_report: false,
  can_view_product_report: false,
  can_view_staff_report: false,
  // Manager overrides
  can_approve_discounts: false,
  can_approve_refunds: false,
  can_unlock_functions: false,
  // Settings
  can_edit_products: false,
  can_edit_categories: false,
  can_edit_pos_settings: false,
} as const

export type PosPermissionKey = keyof typeof POS_PERMISSIONS

export const PERMISSION_LABELS: Record<PosPermissionKey, string> = {
  can_process_sale: 'Process sales',
  can_apply_discount: 'Apply discounts',
  can_apply_discount_over_10pct: 'Discounts over 10%',
  can_void_item: 'Void items',
  can_void_sale: 'Void sales',
  can_process_refund: 'Process refunds',
  can_override_price: 'Override price',
  can_add_notes_to_sale: 'Add notes to sale',
  can_open_cash_drawer: 'Open cash drawer',
  can_view_cash_session: 'View cash session',
  can_close_cash_session: 'Close cash session',
  can_view_float: 'View float',
  can_view_customers: 'View customers',
  can_add_customer: 'Add customers',
  can_edit_customer: 'Edit customers',
  can_redeem_loyalty: 'Redeem loyalty',
  can_view_stock: 'View stock levels',
  can_adjust_stock: 'Adjust stock',
  can_receive_order: 'Receive orders',
  can_view_roster: 'View roster',
  can_clock_in_out: 'Clock in/out',
  can_view_other_timesheets: 'View other timesheets',
  can_view_daily_report: 'View daily report',
  can_view_product_report: 'View product report',
  can_view_staff_report: 'View staff report',
  can_approve_discounts: 'Approve discounts (override)',
  can_approve_refunds: 'Approve refunds (override)',
  can_unlock_functions: 'Unlock restricted functions',
  can_edit_products: 'Edit products',
  can_edit_categories: 'Edit categories',
  can_edit_pos_settings: 'Edit POS settings',
}

export const ROLE_DEFAULTS: Record<string, Partial<Record<PosPermissionKey, boolean>>> = {
  owner: Object.fromEntries(Object.keys(POS_PERMISSIONS).map(k => [k, true])) as Record<PosPermissionKey, boolean>,
  manager: {
    can_process_sale: true,
    can_apply_discount: true,
    can_apply_discount_over_10pct: true,
    can_void_item: true,
    can_void_sale: true,
    can_process_refund: true,
    can_override_price: true,
    can_add_notes_to_sale: true,
    can_open_cash_drawer: true,
    can_view_cash_session: true,
    can_close_cash_session: true,
    can_view_float: true,
    can_view_customers: true,
    can_add_customer: true,
    can_edit_customer: true,
    can_redeem_loyalty: true,
    can_view_stock: true,
    can_adjust_stock: true,
    can_receive_order: true,
    can_view_roster: true,
    can_clock_in_out: true,
    can_view_other_timesheets: true,
    can_view_daily_report: true,
    can_view_product_report: true,
    can_approve_discounts: true,
    can_approve_refunds: true,
    can_unlock_functions: true,
  },
  cashier: {
    can_process_sale: true,
    can_add_notes_to_sale: true,
    can_open_cash_drawer: true,
    can_view_customers: true,
    can_add_customer: true,
    can_redeem_loyalty: true,
    can_view_stock: true,
    can_view_roster: true,
    can_clock_in_out: true,
  },
  supervisor: {
    can_process_sale: true,
    can_apply_discount: true,
    can_void_item: true,
    can_process_refund: true,
    can_add_notes_to_sale: true,
    can_open_cash_drawer: true,
    can_view_cash_session: true,
    can_view_customers: true,
    can_add_customer: true,
    can_edit_customer: true,
    can_redeem_loyalty: true,
    can_view_stock: true,
    can_view_roster: true,
    can_clock_in_out: true,
    can_view_other_timesheets: true,
    can_view_daily_report: true,
    can_approve_discounts: true,
  },
}
