import type { Metadata } from 'next'
import { supabaseAdmin } from '@/lib/supabase-admin'

interface Props {
  params: Promise<{ token: string }>
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { token } = await params
  const { data } = await supabaseAdmin
    .from('aria_task_outputs')
    .select('title')
    .eq('share_token', token)
    .eq('is_public', true)
    .maybeSingle()
  const title = (data as { title?: string } | null)?.title ?? 'Aria OS Report'
  return {
    title: title + ' — Aria OS',
    description: 'Business intelligence report generated by Aria OS',
    openGraph: {
      title: title + ' — Aria OS',
      description: 'Business intelligence report generated by Aria OS',
      siteName: 'Aria OS',
    },
  }
}

export default async function ShareOutputPage({ params }: Props) {
  const { token } = await params

  const { data: output } = await supabaseAdmin
    .from('aria_task_outputs')
    .select('id, title, render_html, output_kind, created_at')
    .eq('share_token', token)
    .eq('is_public', true)
    .maybeSingle()

  if (!output) {
    return (
      <div style={{ minHeight: '100vh', background: '#0f1a13', display: 'flex', alignItems: 'center', justifyContent: 'center', fontFamily: 'Inter, sans-serif' }}>
        <div style={{ textAlign: 'center' }}>
          <div style={{ fontSize: 48, marginBottom: 16 }}>🔒</div>
          <h1 style={{ color: '#fff', marginBottom: 8, fontSize: 20 }}>Report not found</h1>
          <p style={{ color: '#6b7280', fontSize: 14 }}>This link may have expired or been removed.</p>
        </div>
      </div>
    )
  }

  const title = (output as { title?: string }).title ?? 'Aria OS Report'
  const html = (output as { render_html?: string }).render_html ?? ''
  const createdAt = (output as { created_at?: string }).created_at ?? ''
  const dateStr = createdAt
    ? new Date(createdAt).toLocaleDateString('en-AU', { day: 'numeric', month: 'long', year: 'numeric' })
    : ''

  return (
    <div style={{ minHeight: '100vh', background: '#0f1a13', fontFamily: 'Inter, sans-serif' }}>
      <header style={{
        background: 'rgba(45,82,64,0.95)',
        borderBottom: '1px solid rgba(127,184,151,0.2)',
        padding: '12px 24px',
        display: 'flex',
        alignItems: 'center',
        gap: 12,
        position: 'sticky',
        top: 0,
        zIndex: 10,
      }}>
        <span style={{ fontSize: 22, fontWeight: 700, color: '#7FB897', fontFamily: 'Georgia, serif', fontStyle: 'italic' }}>Aria OS</span>
        <span style={{ color: '#4b5563', fontSize: 14 }}>|</span>
        <span style={{ color: '#e5e7eb', fontSize: 14, fontWeight: 500, flex: 1, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{title}</span>
        {dateStr && <span style={{ color: '#6b7280', fontSize: 12, whiteSpace: 'nowrap' }}>{dateStr}</span>}
      </header>

      <main style={{ padding: '24px 16px', maxWidth: 1200, margin: '0 auto' }}>
        {html ? (
          <iframe
            srcDoc={html}
            style={{ width: '100%', minHeight: 600, border: 'none', borderRadius: 12, background: '#fff' }}
            title={title}
            sandbox="allow-scripts"
          />
        ) : (
          <div style={{ color: '#6b7280', textAlign: 'center', padding: 48, fontSize: 14 }}>No content available</div>
        )}
      </main>

      <footer style={{ textAlign: 'center', padding: '20px 16px', color: '#4b5563', fontSize: 12, borderTop: '1px solid rgba(127,184,151,0.1)', marginTop: 24 }}>
        Generated by{' '}
        <a href="https://ariaos.site" style={{ color: '#7FB897', textDecoration: 'none' }}>Aria OS</a>
        {' '}· AI business intelligence for Australian small businesses
      </footer>
    </div>
  )
}
