export const runtime = 'nodejs'
export const dynamic = 'force-dynamic'
export const maxDuration = 60

import { NextResponse } from 'next/server'
import { createServerSupabaseClient } from '@/lib/supabase-server'
import { supabaseAdmin } from '@/lib/supabase-admin'
import { exportDeliverablePdf } from '@/lib/aria/deliverable-pdf'

async function getBid(supabase: ReturnType<typeof createServerSupabaseClient>, userId: string): Promise<string | null> {
  const { data: active } = await supabase.from('user_active_business').select('business_id').eq('user_id', userId).maybeSingle()
  if (active?.business_id) return active.business_id as string
  const { data } = await supabase.from('businesses').select('id').eq('user_id', userId).eq('is_active', true).limit(1).maybeSingle()
  return data?.id ?? null
}

export async function POST(req: Request) {
  const supabase = createServerSupabaseClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const bid = await getBid(supabase, user.id)
  if (!bid) return NextResponse.json({ error: 'No business found' }, { status: 404 })

  const body = await req.json() as { outputId?: string; recipients?: string[]; subject?: string }
  if (!body.outputId) return NextResponse.json({ error: 'outputId required' }, { status: 400 })
  const recipients = body.recipients ?? [user.email ?? '']
  if (!recipients.length || !recipients[0]) return NextResponse.json({ error: 'recipients required' }, { status: 400 })

  const resendKey = process.env.RESEND_API_KEY
  if (!resendKey) return NextResponse.json({ error: 'Email not configured (RESEND_API_KEY missing)' }, { status: 503 })

  const start = Date.now()
  try {
    // 1. Get or generate PDF (idempotent)
    const pdfUrl = await exportDeliverablePdf(body.outputId, bid)

    // 2. Fetch the output row for title
    const { data: output } = await supabaseAdmin
      .from('aria_task_outputs')
      .select('title, output_kind')
      .eq('id', body.outputId)
      .maybeSingle()

    const title = (output as { title?: string } | null)?.title ?? 'Business Report'
    const subject = body.subject ?? ('Aria OS: ' + title)

    // 3. Fetch PDF buffer from blob URL
    const pdfRes = await fetch(pdfUrl)
    if (!pdfRes.ok) throw new Error('Failed to fetch PDF for email attachment')
    const pdfArrayBuffer = await pdfRes.arrayBuffer()
    const b64 = Buffer.from(pdfArrayBuffer).toString('base64')

    // 4. Send via Resend — reuse template style from send-scheduled-reports
    const emailHtml = '<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"></head>'
      + '<body style="margin:0;padding:0;background:#f3f4f6;font-family:Inter,Arial,sans-serif">'
      + '<div style="max-width:540px;margin:32px auto;background:#fff;border-radius:12px;overflow:hidden;box-shadow:0 1px 3px rgba(0,0,0,0.1)">'
      + '<div style="background:#0E1611;padding:24px 28px"><div style="font-family:Georgia,serif;font-style:italic;font-size:20px;color:#7FB897">Aria OS</div>'
      + '<div style="color:#9ca3af;font-size:12px;margin-top:3px">Business Intelligence Report</div></div>'
      + '<div style="padding:24px 28px">'
      + '<p style="margin:0 0 14px;font-size:15px;color:#111827;font-weight:600">' + title + '</p>'
      + '<p style="margin:0 0 18px;font-size:14px;color:#374151">Your deliverable is attached as a PDF.</p>'
      + '<p style="margin:20px 0 0;font-size:12px;color:#9ca3af;border-top:1px solid #e5e7eb;padding-top:14px">Generated by Aria OS. Confidential.</p>'
      + '</div></div></body></html>'

    const filename = title.toLowerCase().replace(/[^a-z0-9]+/g, '-').slice(0, 40) + '.pdf'

    const res = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: { Authorization: 'Bearer ' + resendKey, 'Content-Type': 'application/json' },
      body: JSON.stringify({
        from: 'Aria <aria@ariaos.site>',
        to: recipients,
        subject,
        html: emailHtml,
        attachments: [{ content: b64, filename, type: 'application/pdf', disposition: 'attachment' }],
      }),
    })

    if (!res.ok) {
      const text = await res.text().catch(() => res.statusText)
      throw new Error('Resend error: ' + text.slice(0, 200))
    }

    await supabaseAdmin.from('aria_ai_calls').insert({
      business_id: bid,
      agent_key: 'deliverable_email',
      provider: 'other',
      model_id: 'resend',
      model_provider: 'other',
      role: 'document',
      cost_usd_cents: 0,
      latency_ms: Date.now() - start,
      success: true,
      request_summary: 'email/' + body.outputId + '/' + recipients.length + '_recipients',
      response_summary: 'sent to ' + recipients.join(', ').slice(0, 200),
    })

    return NextResponse.json({ sent: true, recipients })
  } catch (e) {
    return NextResponse.json({ error: (e as Error).message }, { status: 500 })
  }
}
