// CANON-RAIL-1 — the enforcement rail's CI guard.
//
// Every prior fix in this codebase (getRevenueSnapshot, get-bid.ts, resolveOwnerBusinessId.ts,
// ComputeResult/Provenance) built a correct, importable canonical helper and stopped there —
// adoption never exceeded ~9-15% (see ARIA-ARCHAEOLOGY-1-REPORT.md) because nothing FORCED a new
// file to use it. This script is that missing forcing mechanism for CI: it fails the build when a
// diff ADDS a new instance of one of the three known-wrong patterns, while leaving the ~329
// pre-existing instances untouched (grandfathered — migrating them is a separate sprint, not this
// guard's job). Only NEW lines in the diff are scanned, never the whole repo.
//
// Patterns blocked:
//   1. A new file-local business-id resolver (`function getBid(...)`, `getBusinessId`, `getBiz`,
//      in function or const-arrow form) — use withBusinessContext (src/lib/api/with-error-capture.ts)
//      or import resolveOwnerBusinessId (src/lib/community/resolveOwnerBusinessId.ts) instead.
//   2. `.neq('status', 'voided')` on any query — the wrong RULE 6 filter; use `.eq('status',
//      'completed')`, or better, getRevenueSnapshot()/getRevenueForRange() for revenue figures.
//   3. A hand-rolled revenue sum (`.reduce(` over a `total_amount` field) in a file outside the
//      canonical compute layer — use getRevenueSnapshot()/getRevenueForRange() instead.
//   4. SECURITY-P5 — a new/modified supabase/migrations/*.sql file that creates a SECURITY
//      DEFINER function with no REVOKE anywhere in the same file. Postgres grants EXECUTE to
//      PUBLIC by default on function creation; this is the exact root cause behind all 24
//      anon/authenticated-executable DEFINER functions SECURITY-P5 found and closed
//      (loyalty_preload_*, credit_image_credits, decrement_numeric/increment_numeric's dynamic-
//      SQL arbitrary-column primitive, create_product_draft's cross-tenant injection gap, etc.
//      — see supabase/migrations/202607270{1,2,3,4}0000_security_p5_tier*.sql). A migration
//      that creates a DEFINER function must explicitly REVOKE EXECUTE FROM PUBLIC/anon (and
//      authenticated, unless the function is genuinely self-guarding via auth.uid()) in the
//      same file — this rule fails the build if it doesn't, before the gap ever reaches prod.
//
// Usage:
//   npx tsx scripts/canon-rail-guard.ts                  # CI default: diff origin/main...HEAD
//   npx tsx scripts/canon-rail-guard.ts --base=<ref>      # diff against a specific ref
//   npx tsx scripts/canon-rail-guard.ts --working-tree    # diff uncommitted tracked/intent-to-add changes (local dev)
//
// Exit code 0 = no new violations. Exit code 1 = at least one new violation (printed to stdout).

import { execSync } from 'node:child_process'

const EXEMPT_PATHS = [
  'src/lib/community/resolveOwnerBusinessId.ts', // the canonical resolver itself
  'src/lib/auth/get-bid.ts',                     // pre-existing resolver, retirement is a separate migration sprint
  'src/lib/api/with-error-capture.ts',           // the rail itself calls resolveOwnerBusinessId
  'src/lib/aria/revenue-snapshot.ts',            // the canonical revenue compute layer
  'src/lib/aria/compute/',                       // the canonical compute layer
  'scripts/canon-rail-guard.ts',                 // this file quotes the patterns it blocks
  // MS7 phase 5 — the two comms chokepoints ARE the rail; they are the only files allowed to
  // call the provider directly. Everything else must go through sendSMS() / sendWhatsApp().
  'src/lib/clicksend.ts',
  'src/lib/whatsapp.ts',
  // MS10 phase 1 — the cost rail itself: the resolver must read the raw columns to rank them, and
  // stock-value's query predates its MS9 rerouting through the resolver.
  'src/lib/inventory/resolve-cost.ts',
  'src/lib/inventory/stock-value.ts',
]

// WALL 1 (M13 phase 4) — THE MODEL-GATEWAY GRANDFATHER LIST. IT CAN ONLY SHRINK.
//
// Every file below constructs a provider client or calls a model directly: `new Anthropic(`,
// `.messages.create(`, `GoogleGenerativeAI` or `generateContent(`. Each is its own decision about
// failover (there is none), its own cost logging (or none — the ledger undercounts by roughly
// half), and its own idea of what Aria is. M12 found where that ends: a lane that answered a cafe
// owner's question about his business with advice about his bedroom.
//
// THIS LIST IS THE MIGRATION BACKLOG. Generated by scanning the tree with comments stripped, so a
// file that merely describes the pattern is not grandfathered into being allowed to use it. New
// files are blocked outright; these are allowed until migrated onto callModel()
// (src/lib/ai/gateway.ts). The count is reported in RUN-M13.md before and after each migration
// batch, and `w1-allowlist-only-shrinks.test.ts` fails if it ever grows.
const MODEL_GATEWAY_ALLOWLIST = [
  'src/app/api/agent/route.ts',
  'src/app/api/agents/bas/classify-products/route.ts',
  'src/app/api/aria/activity-narrative/route.ts',
  'src/app/api/aria/auto-review/route.ts',
  'src/app/api/aria/autopilot/route.ts',
  'src/app/api/aria/bom-suggest/route.ts',
  'src/app/api/aria/booking-insights/route.ts',
  'src/app/api/aria/briefing/route.ts',
  'src/app/api/aria/bundle-builder/route.ts',
  'src/app/api/aria/cash-commentary/route.ts',
  'src/app/api/aria/cashup-intelligence/route.ts',
  'src/app/api/aria/command/route.ts',
  'src/app/api/aria/competitive-brief/route.ts',
  'src/app/api/aria/competitor-opportunities/route.ts',
  'src/app/api/aria/competitor-prices/route.ts',
  'src/app/api/aria/competitor-review-analysis/route.ts',
  'src/app/api/aria/competitor-watches/route.ts',
  'src/app/api/aria/customer-insight/route.ts',
  'src/app/api/aria/customer-intel/route.ts',
  'src/app/api/aria/daily-briefing/route.ts',
  'src/app/api/aria/daily-narrative/route.ts',
  'src/app/api/aria/delivery-prediction/route.ts',
  'src/app/api/aria/draft-review-reply/route.ts',
  'src/app/api/aria/dynamic-pricing/route.ts',
  'src/app/api/aria/explain-metric/route.ts',
  'src/app/api/aria/feature-builder/route.ts',
  'src/app/api/aria/first-insight/route.ts',
  'src/app/api/aria/generate-promotion/route.ts',
  'src/app/api/aria/generate-purchase-orders/route.ts',
  'src/app/api/aria/generate-quote/route.ts',
  'src/app/api/aria/grn-assist/route.ts',
  'src/app/api/aria/influencer/generate/route.ts',
  'src/app/api/aria/inventory-insight/route.ts',
  'src/app/api/aria/marketing-campaigns/route.ts',
  'src/app/api/aria/menu-optimisation/route.ts',
  'src/app/api/aria/missed-demand-analysis/route.ts',
  'src/app/api/aria/page-insight/route.ts',
  'src/app/api/aria/pos-chat/route.ts',
  'src/app/api/aria/pos-end-of-day/route.ts',
  'src/app/api/aria/pos-insight/route.ts',
  'src/app/api/aria/price-check/route.ts',
  'src/app/api/aria/price-intelligence/route.ts',
  'src/app/api/aria/product-insights/route.ts',
  'src/app/api/aria/product-suggest/route.ts',
  'src/app/api/aria/quote-followup/route.ts',
  'src/app/api/aria/receipt-scan/route.ts',
  'src/app/api/aria/recipe-cost-optimiser/route.ts',
  'src/app/api/aria/recipe-scale/route.ts',
  'src/app/api/aria/reorder-forecast/route.ts',
  'src/app/api/aria/roster/route.ts',
  'src/app/api/aria/sale-insight/route.ts',
  'src/app/api/aria/shift-analysis/route.ts',
  'src/app/api/aria/slow-day/route.ts',
  'src/app/api/aria/social-intelligence/route.ts',
  'src/app/api/aria/social-learning/route.ts',
  'src/app/api/aria/social-suggest/route.ts',
  'src/app/api/aria/staff-schedule/route.ts',
  'src/app/api/aria/staff-talk/route.ts',
  'src/app/api/aria/staff-visa-insight/route.ts',
  'src/app/api/aria/stocktake-intelligence/route.ts',
  'src/app/api/aria/studio/route.ts',
  'src/app/api/aria/supplier-insights/route.ts',
  'src/app/api/aria/supplier-margin-intelligence/route.ts',
  'src/app/api/aria/supplier-reorder/route.ts',
  'src/app/api/aria/supplier-savings/route.ts',
  'src/app/api/aria/talk/route.ts',
  'src/app/api/aria/theft-detection/route.ts',
  'src/app/api/aria/upload/route.ts',
  'src/app/api/aria/variance/route.ts',
  'src/app/api/aria/warehouse-intelligence/route.ts',
  'src/app/api/aria/warehouse-slotting/route.ts',
  'src/app/api/aria/weekly-report/route.ts',
  'src/app/api/aria/widget-insights/route.ts',
  'src/app/api/aria/winback-compose/route.ts',
  'src/app/api/aria/winback-message/route.ts',
  'src/app/api/aria/winback/route.ts',
  'src/app/api/bookings/aria-suggest/route.ts',
  'src/app/api/builder/route.ts',
  'src/app/api/chat/route.ts',
  'src/app/api/community/owner/ai-draft/route.ts',
  'src/app/api/community/owner/marketer/plan/route.ts',
  'src/app/api/cron/parcel-insights/route.ts',
  'src/app/api/customers/[id]/ai-summary/route.ts',
  'src/app/api/customers/[id]/summarise/route.ts',
  'src/app/api/customers/[id]/winback/route.ts',
  'src/app/api/customers/import-map/route.ts',
  'src/app/api/delivery/analytics/route.ts',
  'src/app/api/documents/generate/route.ts',
  'src/app/api/execute-autofix/route.ts',
  'src/app/api/health/deep/route.ts',
  'src/app/api/instore/insights/route.ts',
  'src/app/api/invoices/draft-ai/route.ts',
  'src/app/api/invoices/reminder/route.ts',
  'src/app/api/loyalty/revenue-forecast/route.ts',
  'src/app/api/plugins/route.ts',
  'src/app/api/pos/agents/[type]/route.ts',
  'src/app/api/pos/cash-flow/analysis/route.ts',
  'src/app/api/pos/customer-greet/route.ts',
  'src/app/api/pos/customers/insight/route.ts',
  'src/app/api/pos/customers/sms-draft/route.ts',
  'src/app/api/pos/display-suggestions/route.ts',
  'src/app/api/pos/gift-cards/aria-check/route.ts',
  'src/app/api/pos/import/csv/route.ts',
  'src/app/api/pos/import/map-columns/route.ts',
  'src/app/api/pos/migrate/route.ts',
  'src/app/api/pos/online-orders/aria-upsell/route.ts',
  'src/app/api/pos/production-plan/route.ts',
  'src/app/api/pos/quick-promo-suggest/route.ts',
  'src/app/api/pos/recipes/[id]/allergens/route.ts',
  'src/app/api/pos/recipes/import/route.ts',
  'src/app/api/pos/shift-audits/route.ts',
  'src/app/api/pos/shift-reports/route.ts',
  'src/app/api/products/barcode-lookup/route.ts',
  'src/app/api/project/generate/route.ts',
  'src/app/api/public/instore/chat/route.ts',
  'src/app/api/public/instore/recipe/route.ts',
  'src/app/api/public/menu/[business_id]/descriptions/route.ts',
  'src/app/api/public/widget/chat/route.ts',
  'src/app/api/recipes/compare/route.ts',
  'src/app/api/recipes/import/route.ts',
  'src/app/api/reels/ai-edit/route.ts',
  'src/app/api/reels/captions/route.ts',
  'src/app/api/reels/ideas/route.ts',
  'src/app/api/research/route.ts',
  'src/app/api/screenshot-to-code/route.ts',
  'src/app/api/sentry/webhook/route.ts',
  'src/app/api/seo/competitor-analysis/route.ts',
  'src/app/api/seo/competitors/route.ts',
  'src/app/api/seo/generate-fix/route.ts',
  'src/app/api/seo/keyword-suggestions/route.ts',
  'src/app/api/seo/local-scan/route.ts',
  'src/app/api/seo/recommendations/route.ts',
  'src/app/api/social/calendar/route.ts',
  'src/app/api/social/growth-post/route.ts',
  'src/app/api/social/media/route.ts',
  'src/app/api/social/owner-request/route.ts',
  'src/app/api/suppliers/price-lists/route.ts',
  'src/app/api/tickets/ai-suggest/route.ts',
  'src/app/api/tickets/price-schedules/route.ts',
  'src/app/api/training/draft-from-recipe/route.ts',
  'src/app/api/visa/chat/route.ts',
  'src/app/api/visa/generate-doc/route.ts',
  'src/app/api/visa/monitor/route.ts',
  'src/app/api/warehouse/ai-order-suggestions/route.ts',
  'src/app/api/warehouse/purchase-orders/[id]/receive/route.ts',
  'src/app/api/wholesale/aria-intelligence/route.ts',
  'src/app/api/wholesale/orders/aria-suggest/route.ts',
  'src/app/api/wholesale/orders/from-email/route.ts',
  'src/app/api/widget/chat/route.ts',
  'src/app/dashboard/social-calendar/page.tsx',
  'src/lib/agents/aeo-monitor.ts',
  'src/lib/agents/base-agent.ts',
  'src/lib/ai-router.ts',
  'src/lib/ai/gateway.test.ts',
  'src/lib/aria-insights.ts',
  'src/lib/aria/agents/automation-agent.ts',
  'src/lib/aria/agents/message-agent.ts',
  'src/lib/aria/agents/orchestrator.ts',
  'src/lib/aria/agents/query-agent.ts',
  'src/lib/aria/agents/rostering-agent.ts',
  'src/lib/aria/council.ts',
  'src/lib/aria/deliverables.ts',
  'src/lib/aria/intelligence/competitor.ts',
  'src/lib/aria/market-prices.ts',
  'src/lib/aria/model-router.ts',
  'src/lib/aria/parallel-orchestrator.ts',
  'src/lib/aria/providers/anthropic.ts',
  'src/lib/aria/response-validator.ts',
  'src/lib/community/abuse-guard.ts',
  'src/lib/community/privacy-guard.ts',
  'src/lib/gemini.ts',
  'src/lib/intelligence/agent.ts',
  'src/lib/pos/ai-split.ts',
  'src/lib/pos/receipt-ocr.ts',
  'src/lib/reports/weekly-ai.ts',
  'src/lib/seo/ai-fix.ts',
]

/** The only two places allowed to touch a provider SDK at all. */
const MODEL_GATEWAY_HOMES = [
  'src/lib/ai/',
  'src/lib/aria/providers/',
]

// WALL 6 (M13 phase 1) — THE READ-THE-ERROR GRANDFATHER LIST.
//
// Only NEW diff lines are scanned, so pre-existing violations are already grandfathered without
// being named. This list is for whole AREAS that are exempt by nature rather than by age:
//
//   · generated types — no runtime calls at all
//   · the Supabase client factories themselves — they construct the client, they do not query
//
// It is deliberately tiny. A file added here is a file allowed to fail silently, and the migration
// backlog (counted by directory in RUN-M13.md) is meant to shrink, not this list to grow.
const READ_THE_ERROR_ALLOWLIST = [
  'src/types/database.types.ts',
  'src/lib/supabase-admin.ts',
  'src/lib/supabase-server.ts',
]

// M12 phase 3 — the ONLY files allowed to contain an Ask Aria persona string. constitution.ts IS
// the constitution; assemble.ts is the rail that prepends it. Everything else in an Ask Aria path
// must go through assembleAriaPrompt(). Deliberately two entries and no more — a third would mean
// the rail had been routed around.
const ASK_ARIA_PROMPT_ALLOWLIST = [
  'src/lib/aria/prompt/constitution.ts',
  'src/lib/aria/prompt/assemble.ts',
]

// MS10 phase 1 — THE COST RAIL'S GRANDFATHER LIST, explicit and shrinking.
//
// resolve-cost.ts is the one honest way to get a product cost: it ranks a recorded transaction
// above the catalogue estimate, reports unknown as null (never 0), and carries provenance. These
// 53 files still read pos_products.cost_price directly in a .select(), so they can still show the
// fabricated price*0.4 figure (72 of 76 active costed products carry it to the cent) while
// resolver-backed surfaces show the truth. Two answers to one question is worse than one wrong
// answer, because it looks fixed.
//
// This is an ALLOWLIST, not a blanket exemption: each file is named so migrating one and removing
// it here is a measurable step, and adding a NEW direct read anywhere else fails the push. The
// deliverable metric is this list's length. Started at 53 (MS10 phase 1); 50 after phase 2 (price-check, product-insights, price-intelligence); 48 after phase 3 (both hypothesis files); 44 after MS11 phase 1 (pos-chat, guidance, owner-agent, replenishment-agent); 42 after MS11 phase 2 (reports/[type], bundle-builder — closure and page-insight stay: their reads are sale-line/movement SNAPSHOTS, the correct historical source, not catalogue reads).
// MS12 PHASE 6 — files that may still WRITE the tombstoned UOM columns (items_per_case,
// case_quantity, cases_*, sell_uom; see src/lib/inventory/uom.ts for the tombstone record).
// These are the edit-form/mapping surfaces MS12 phase 5 deliberately left (decision table:
// import fixed, edit forms listed) — everything else must write the canonical
// purchase_uom/purchase_uom_qty pair. Shrink this list; never grow it.
const UOM_TOMBSTONE_WRITE_ALLOWLIST = [
  'src/app/api/pos/products/route.ts',
  'src/app/api/pos/products/[id]/route.ts',
  'src/app/api/pos/import/map-columns/route.ts',
  'src/components/pos/ProductForm.tsx',
  'src/components/products/edit/ProductEditShell.tsx',
  'src/components/products/edit/tabs/InventoryTab.tsx',
  'src/components/products/industry/RetailProductFields.tsx',
]

// MS15 PHASE 1 — THE MODEL GATEWAY'S GRANDFATHER LIST.
//
// src/lib/aria/model-router.ts is the gateway: one place that logs provider, model, tokens,
// latency, cost and outcome for a model call. 174 files instantiate a provider SDK directly and
// therefore log whatever they each remember to log — which is how model-router.ts and ai-router.ts
// went months logging NOTHING (AI-COST-AUDIT-1), and how 93 production calls are still recorded as
// costing zero because nobody priced their model.
//
// Migrating 174 sites in one sprint is not the move (measured adoption of a new helper without a
// rail in this repo: 9-15%). This is the rail: every existing site is grandfathered BY NAME, and a
// NEW direct instantiation fails the push. Shrink this list; never grow it.
const MODEL_SDK_ALLOWLIST = [
  'src/app/api/agent/route.ts',
  'src/app/api/agents/bas/classify-products/route.ts',
  'src/app/api/aria/activity-narrative/route.ts',
  'src/app/api/aria/auto-review/route.ts',
  'src/app/api/aria/autopilot/route.ts',
  'src/app/api/aria/bom-suggest/route.ts',
  'src/app/api/aria/booking-insights/route.ts',
  'src/app/api/aria/briefing/route.ts',
  'src/app/api/aria/bundle-builder/route.ts',
  'src/app/api/aria/cash-commentary/route.ts',
  'src/app/api/aria/cashup-intelligence/route.ts',
  'src/app/api/aria/command/route.ts',
  'src/app/api/aria/competitive-brief/route.ts',
  'src/app/api/aria/competitor-opportunities/route.ts',
  'src/app/api/aria/competitor-prices/route.ts',
  'src/app/api/aria/competitor-review-analysis/route.ts',
  'src/app/api/aria/customer-insight/route.ts',
  'src/app/api/aria/customer-intel/route.ts',
  'src/app/api/aria/daily-narrative/route.ts',
  'src/app/api/aria/delivery-prediction/route.ts',
  'src/app/api/aria/dynamic-pricing/route.ts',
  'src/app/api/aria/explain-metric/route.ts',
  'src/app/api/aria/feature-builder/route.ts',
  'src/app/api/aria/first-insight/route.ts',
  'src/app/api/aria/generate-promotion/route.ts',
  'src/app/api/aria/generate-purchase-orders/route.ts',
  'src/app/api/aria/generate-quote/route.ts',
  'src/app/api/aria/grn-assist/route.ts',
  'src/app/api/aria/influencer/generate/route.ts',
  'src/app/api/aria/inventory-insight/route.ts',
  'src/app/api/aria/marketing-campaigns/route.ts',
  'src/app/api/aria/menu-optimisation/route.ts',
  'src/app/api/aria/missed-demand-analysis/route.ts',
  'src/app/api/aria/page-insight/route.ts',
  'src/app/api/aria/pos-chat/route.ts',
  'src/app/api/aria/pos-end-of-day/route.ts',
  'src/app/api/aria/pos-insight/route.ts',
  'src/app/api/aria/price-check/route.ts',
  'src/app/api/aria/price-intelligence/route.ts',
  'src/app/api/aria/product-insights/route.ts',
  'src/app/api/aria/product-suggest/route.ts',
  'src/app/api/aria/quote-followup/route.ts',
  'src/app/api/aria/receipt-scan/route.ts',
  'src/app/api/aria/recipe-cost-optimiser/route.ts',
  'src/app/api/aria/recipe-scale/route.ts',
  'src/app/api/aria/reorder-forecast/route.ts',
  'src/app/api/aria/roster/route.ts',
  'src/app/api/aria/sale-insight/route.ts',
  'src/app/api/aria/shift-analysis/route.ts',
  'src/app/api/aria/slow-day/route.ts',
  'src/app/api/aria/social-learning/route.ts',
  'src/app/api/aria/staff-schedule/route.ts',
  'src/app/api/aria/staff-talk/route.ts',
  'src/app/api/aria/staff-visa-insight/route.ts',
  'src/app/api/aria/stocktake-intelligence/route.ts',
  'src/app/api/aria/studio/route.ts',
  'src/app/api/aria/supplier-insights/route.ts',
  'src/app/api/aria/supplier-margin-intelligence/route.ts',
  'src/app/api/aria/supplier-reorder/route.ts',
  'src/app/api/aria/supplier-savings/route.ts',
  'src/app/api/aria/talk/route.ts',
  'src/app/api/aria/theft-detection/route.ts',
  'src/app/api/aria/upload/route.ts',
  'src/app/api/aria/variance/route.ts',
  'src/app/api/aria/warehouse-intelligence/route.ts',
  'src/app/api/aria/warehouse-slotting/route.ts',
  'src/app/api/aria/weekly-report/route.ts',
  'src/app/api/aria/widget-insights/route.ts',
  'src/app/api/aria/winback-compose/route.ts',
  'src/app/api/aria/winback-message/route.ts',
  'src/app/api/aria/winback-send/route.ts',
  'src/app/api/aria/winback/route.ts',
  'src/app/api/bookings/aria-suggest/route.ts',
  'src/app/api/builder/route.ts',
  'src/app/api/chat/route.ts',
  'src/app/api/community/owner/ai-draft/route.ts',
  'src/app/api/community/owner/marketer/plan/route.ts',
  'src/app/api/cron/parcel-insights/route.ts',
  'src/app/api/customers/[id]/ai-summary/route.ts',
  'src/app/api/customers/[id]/summarise/route.ts',
  'src/app/api/customers/[id]/winback/route.ts',
  'src/app/api/customers/import-map/route.ts',
  'src/app/api/delivery/analytics/route.ts',
  'src/app/api/documents/generate/route.ts',
  'src/app/api/execute-autofix/route.ts',
  'src/app/api/health/deep/route.ts',
  'src/app/api/instore/insights/route.ts',
  'src/app/api/invoices/draft-ai/route.ts',
  'src/app/api/invoices/reminder/route.ts',
  'src/app/api/loyalty/revenue-forecast/route.ts',
  'src/app/api/plugins/route.ts',
  'src/app/api/pos/agents/[type]/route.ts',
  'src/app/api/pos/cash-flow/analysis/route.ts',
  'src/app/api/pos/customer-greet/route.ts',
  'src/app/api/pos/customers/insight/route.ts',
  'src/app/api/pos/customers/sms-draft/route.ts',
  'src/app/api/pos/display-suggestions/route.ts',
  'src/app/api/pos/gift-cards/aria-check/route.ts',
  'src/app/api/pos/import/csv/route.ts',
  'src/app/api/pos/import/map-columns/route.ts',
  'src/app/api/pos/menu-extract/route.ts',
  'src/app/api/pos/migrate/route.ts',
  'src/app/api/pos/online-orders/aria-upsell/route.ts',
  'src/app/api/pos/production-plan/route.ts',
  'src/app/api/pos/products/generate-image/route.ts',
  'src/app/api/pos/quick-promo-suggest/route.ts',
  'src/app/api/pos/recipes/[id]/allergens/route.ts',
  'src/app/api/pos/recipes/import/route.ts',
  'src/app/api/pos/shift-audits/route.ts',
  'src/app/api/pos/shift-reports/route.ts',
  'src/app/api/products/barcode-lookup/route.ts',
  'src/app/api/project/generate/route.ts',
  'src/app/api/public/instore/chat/route.ts',
  'src/app/api/public/instore/recipe/route.ts',
  'src/app/api/public/menu/[business_id]/descriptions/route.ts',
  'src/app/api/public/widget/chat/route.ts',
  'src/app/api/recipes/compare/route.ts',
  'src/app/api/recipes/import/route.ts',
  'src/app/api/reels/ai-edit/route.ts',
  'src/app/api/reels/captions/route.ts',
  'src/app/api/reels/ideas/route.ts',
  'src/app/api/research/route.ts',
  'src/app/api/screenshot-to-code/route.ts',
  'src/app/api/sentry/webhook/route.ts',
  'src/app/api/seo/competitor-analysis/route.ts',
  'src/app/api/seo/competitors/route.ts',
  'src/app/api/seo/generate-fix/route.ts',
  'src/app/api/seo/keyword-suggestions/route.ts',
  'src/app/api/seo/local-scan/route.ts',
  'src/app/api/seo/recommendations/route.ts',
  'src/app/api/social/calendar/route.ts',
  'src/app/api/social/growth-post/route.ts',
  'src/app/api/social/media/route.ts',
  'src/app/api/social/owner-request/route.ts',
  'src/app/api/suppliers/price-lists/route.ts',
  'src/app/api/tickets/ai-suggest/route.ts',
  'src/app/api/tickets/price-schedules/route.ts',
  'src/app/api/training/draft-from-recipe/route.ts',
  'src/app/api/visa/chat/route.ts',
  'src/app/api/visa/generate-doc/route.ts',
  'src/app/api/visa/monitor/route.ts',
  'src/app/api/warehouse/ai-order-suggestions/route.ts',
  'src/app/api/warehouse/purchase-orders/[id]/receive/route.ts',
  'src/app/api/wholesale/aria-intelligence/route.ts',
  'src/app/api/wholesale/orders/aria-suggest/route.ts',
  'src/app/api/wholesale/orders/from-email/route.ts',
  'src/app/api/widget/chat/route.ts',
  'src/lib/agents/aeo-monitor.ts',
  'src/lib/agents/base-agent.ts',
  'src/lib/agents/council.ts',
  'src/lib/ai-router.ts',
  'src/lib/aria-insights.ts',
  'src/lib/aria/agents/automation-agent.ts',
  'src/lib/aria/agents/message-agent.ts',
  'src/lib/aria/agents/orchestrator.ts',
  'src/lib/aria/agents/query-agent.ts',
  'src/lib/aria/agents/rostering-agent.ts',
  'src/lib/aria/council.ts',
  'src/lib/aria/deliverables.ts',
  'src/lib/aria/intelligence/competitor.ts',
  'src/lib/aria/market-prices.ts',
  'src/lib/aria/model-router.ts',
  'src/lib/aria/parallel-orchestrator.ts',
  'src/lib/aria/providers/anthropic.ts',
  'src/lib/aria/response-validator.ts',
  'src/lib/community/abuse-guard.ts',
  'src/lib/community/privacy-guard.ts',
  'src/lib/gemini.ts',
  'src/lib/intelligence/agent.ts',
  'src/lib/loyalty/challenges.ts',
  'src/lib/pos/ai-split.ts',
  'src/lib/pos/receipt-ocr.ts',
  'src/lib/reports/weekly-ai.ts',
  'src/lib/seo/ai-fix.ts',
]

const COST_READ_ALLOWLIST = [
  'src/app/api/admin/businesses/[id]/route.ts',
  'src/app/api/aria/competitor-prices/auto-adjust/route.ts',
  'src/app/api/aria/competitor-prices/route.ts',
  'src/app/api/aria/dynamic-pricing/route.ts',
  'src/app/api/aria/grn-assist/route.ts',
  'src/app/api/aria/inventory-insight/route.ts',
  'src/app/api/aria/page-insight/route.ts',
  'src/app/api/aria/promo-suggest/route.ts',
  'src/app/api/aria/receipt-scan/route.ts',
  'src/app/api/aria/supplier-reorder/route.ts',
  'src/app/api/aria/weekly-order/route.ts',
  'src/app/api/inventory/app/[slug]/expiring/route.ts',
  'src/app/api/pos/cart-intelligence/route.ts',
  'src/app/api/pos/import/barcode-lookup/route.ts',
  'src/app/api/pos/price-tickets/route.ts',
  'src/app/api/pos/products/[id]/route.ts',
  'src/app/api/pos/products/route.ts',
  'src/app/api/pos/products/scan/route.ts',
  'src/app/api/pos/reports/closure/[id]/route.ts',
  'src/app/api/pos/sales/[id]/route.ts',
  'src/app/api/pos/warehouse/replenish/route.ts',
  'src/app/api/suppliers/compare/route.ts',
  'src/app/api/warehouse/ai-order-suggestions/route.ts',
  'src/app/api/warehouse/purchase-orders/[id]/receive/route.ts',
  'src/app/api/warehouse/suppliers/[id]/prices/route.ts',
  'src/app/api/wholesale/orders/[id]/items/route.ts',
  'src/app/api/wholesale/orders/from-email/route.ts',
  'src/lib/agents/flash-revenue-agent.ts',
  'src/lib/agents/inventory-financing-agent.ts',
  'src/lib/agents/menu-engineering-agent.ts',
  'src/lib/agents/pricing-agent.ts',
  'src/lib/agents/reorder-agent.ts',
  'src/lib/agents/waste-elimination-agent.ts',
  'src/lib/aria-tools.ts',
  'src/lib/aria/ask/action-executor.ts',
  'src/lib/aria/ask/action-planner.ts',
  'src/lib/aria/ask/files.ts',
  'src/lib/aria/context.ts',
  'src/lib/aria/deliverables.ts',
  'src/lib/aria/radar/loss-detector.ts',
  'src/lib/inventory/reports.ts',
  'src/lib/reports/weekly-data.ts',
]

interface Violation {
  file: string
  line: number
  rule: string
  text: string
}

function isExempt(file: string): boolean {
  return EXEMPT_PATHS.some(p => file === p || file.startsWith(p))
}

function getDiff(): string {
  const args = process.argv.slice(2)
  const workingTree = args.includes('--working-tree')
  const baseArg = args.find(a => a.startsWith('--base='))
  const base = baseArg ? baseArg.slice('--base='.length) : 'origin/main'

  if (workingTree) {
    // Include brand-new untracked files as additions (git ignores untracked files in a plain
    // `git diff` otherwise) — intent-to-add stages them as empty so the real diff shows as 100% new.
    try { execSync('git add -N .', { stdio: 'ignore' }) } catch { /* best-effort */ }
    return execSync('git diff --unified=0 -- "*.ts" "*.tsx" "supabase/migrations/*.sql"', { encoding: 'utf8', maxBuffer: 1024 * 1024 * 64 })
  }

  return execSync(`git diff --unified=0 ${base}...HEAD -- "*.ts" "*.tsx" "supabase/migrations/*.sql"`, { encoding: 'utf8', maxBuffer: 1024 * 1024 * 64 })
}

function scan(diff: string): Violation[] {
  const violations: Violation[] = []
  let currentFile: string | null = null
  let newLineNo = 0
  // Track added lines per-file for the cross-line "revenue sum" heuristic (rule 3 needs both a
  // total_amount reference AND a .reduce( call somewhere in the same file's new lines).
  const addedLinesByFile = new Map<string, Array<{ line: number; text: string }>>()

  for (const raw of diff.split('\n')) {
    if (raw.startsWith('+++ ')) {
      const path = raw.slice(4).replace(/^b\//, '')
      currentFile = path === '/dev/null' ? null : path
      continue
    }
    if (raw.startsWith('@@')) {
      const m = raw.match(/\+(\d+)/)
      newLineNo = m ? parseInt(m[1], 10) : 0
      continue
    }
    const isSql = currentFile?.endsWith('.sql') ?? false
    const isTs = currentFile?.endsWith('.ts') || currentFile?.endsWith('.tsx')
    if (!currentFile || isExempt(currentFile)) continue
    if (!isTs && !isSql) continue
    if (raw.startsWith('+') && !raw.startsWith('+++')) {
      const text = raw.slice(1)

      if (isTs) {
        if (/\b(async\s+)?function\s+(getBid|getBusinessId|getBiz)\s*\(/.test(text) ||
            /\bconst\s+(getBid|getBusinessId|getBiz)\s*[:=]/.test(text)) {
          violations.push({ file: currentFile, line: newLineNo, rule: 'inline-business-id-resolver', text: text.trim() })
        }

        if (/\.neq\(\s*['"]status['"]\s*,\s*['"]voided['"]\s*\)/.test(text)) {
          violations.push({ file: currentFile, line: newLineNo, rule: 'neq-voided-filter', text: text.trim() })
        }

        // MS7 phase 5 — NO NEW DIRECT CALLS TO THE SMS PROVIDER.
        //
        // src/lib/clicksend.ts's sendSMS() is the single SMS chokepoint: it checks per-channel
        // sms_consent, honours the sms_suppression opt-out list, appends the STOP notice to
        // marketing, and writes every attempt (sent/skipped/failed) to sms_send_log. 45 files
        // import it and, as of MS7 phase 4, NOT ONE bypasses it.
        //
        // This rule exists because the rail working today is not the same as the rail working
        // tomorrow. The email side already learned this: a raw fetch around sendEmail() in the CX
        // digest meant no unsubscribe and no suppression check ever ran, and nothing caught it.
        // A new fetch to rest.clicksend.com would reintroduce exactly that, and the send would
        // look completely normal — the only visible difference is an absent sms_send_log row.
        //
        // Scoped to ADDED lines only, like every other rule here, so the two chokepoints and all
        // existing code are untouched.
        if (/rest\.clicksend\.com|api\.clicksend\.com/.test(text)) {
          violations.push({ file: currentFile, line: newLineNo, rule: 'direct-sms-provider-call', text: text.trim() })
        }

        // MS10 phase 1 — NO NEW DIRECT READS OF THE PRODUCT COST COLUMN.
        //
        // A .select() list naming cost_price bypasses resolve-cost.ts, and with it the tier order
        // (recorded transaction beats estimate), the unknown-is-null rule, and provenance. On live
        // data a direct read returns the fabricated price*0.4 figure for 72 of 76 products, so a
        // new one silently reintroduces the ~60%-margin lie somewhere the fixed surfaces can't see.
        // Scoped to ADDED lines; the 53 pre-existing reader files are grandfathered BY NAME in
        // COST_READ_ALLOWLIST above so the migration is measurable file by file.
        if (/\.select\(\s*['"`][^'"`]*\bcost_price\b/.test(text) && !COST_READ_ALLOWLIST.includes(currentFile)) {
          violations.push({ file: currentFile, line: newLineNo, rule: 'direct-cost-read', text: text.trim() })
        }

        // Rule 8 — MS15 phase 1: a NEW direct provider-SDK instantiation. Model calls go through
        // the gateway (src/lib/aria/model-router.ts) so provider, model, tokens, latency, cost and
        // outcome are logged in ONE place. The 174 pre-existing sites are grandfathered by name in
        // MODEL_SDK_ALLOWLIST above.
        if (/new\s+(?:Anthropic|OpenAI|GoogleGenerativeAI)\s*\(/.test(text)
            && !MODEL_SDK_ALLOWLIST.includes(currentFile)) {
          violations.push({ file: currentFile, line: newLineNo, rule: 'direct-model-sdk-call', text: text.trim() })
        }

        // ── WALL 1 (M13 phase 4) — ONE MODEL GATEWAY ─────────────────────────────────────────
        //
        // 171 files construct their own Anthropic client and 162 call .messages.create directly.
        // A helper they MAY call reaches ~14% adoption in this repo (measured, ARIA-ARCHAEOLOGY-1);
        // a wrapper they MUST pass through reaches 73-78%. So: no NEW file may touch a provider SDK
        // outside src/lib/ai/ and src/lib/aria/providers/. Everything else calls callModel().
        //
        // The 171 are grandfathered by name above — that list is the backlog and can only shrink.
        if (currentFile
            && !/\.(test|spec)\.tsx?$/.test(currentFile)
            && !MODEL_GATEWAY_HOMES.some(h => currentFile!.startsWith(h))
            && !MODEL_GATEWAY_ALLOWLIST.includes(currentFile)
            && /new\s+Anthropic\s*\(|\.messages\.create\s*\(|GoogleGenerativeAI|generateContent\s*\(/.test(text)) {
          violations.push({ file: currentFile, line: newLineNo, rule: 'model-call-outside-gateway', text: text.trim() })
        }

        // ── WALL 6 (M13 phase 1) — READ THE ERROR ────────────────────────────────────────────
        //
        // Supabase RESOLVES with { data, error }. It does not throw. So `try { await supabase... }
        // catch {}` catches nothing, and `const { data } = await supabase...` throws the error away
        // before anyone can look at it. Five sprints in a row found the same consequence:
        //
        //   · council-executor.ts's audit insert: proposal_id non-null on 0 of 854 rows. It has
        //     never once landed, and nothing noticed because the error went into a discarded field.
        //   · 95 agent_council_sessions marked 'complete' with 2 proposals between them, ever.
        //   · 2,275 false nightly-sync failure rows.
        //   · recordEvent — the moat spine's ONE writer — swallowed CHECK violations until M11B.
        //   · /api/customers/merge soft-deleted the source row after a rejected write, and returned
        //     200 (RULE 7's incident record).
        //
        // Rule 10a — a destructure that takes `data` and drops `error`.
        // Rule 10b — a bare awaited write whose result is assigned to nothing at all.
        //
        // ONLY NEW LINES ARE SCANNED, so the ~800 pre-existing sites are grandfathered exactly as
        // every rule above grandfathers its predecessors; the backlog is counted by directory in
        // RUN-M13.md. Reads are included deliberately: an unread error on a SELECT is how a caller
        // reports "no rows" when the truth is "we could not find out" — RULE 7, and the reason
        // listLabels/loadPlan throw rather than return [].
        if (currentFile && !/\.(test|spec)\.tsx?$/.test(currentFile) && !READ_THE_ERROR_ALLOWLIST.some(a => currentFile!.startsWith(a))) {
          // 10a: `const { data } = await supabase…` / `const { data: x } = await supabaseAdmin…`
          const destructure = text.match(/const\s*\{([^}]*)\}\s*=\s*await\s+(?:supabase|supabaseAdmin|db)\b/)
          if (destructure && !/\berror\b/.test(destructure[1])) {
            violations.push({ file: currentFile, line: newLineNo, rule: 'supabase-error-not-read', text: text.trim() })
          }
          // 10b: `await supabase.from(...).insert(...)` as a STATEMENT — nothing catches the result.
          // This is council-executor.ts:17 exactly, and recordEvent before M11B.
          if (/^\s*(?:void\s+)?await\s+(?:supabase|supabaseAdmin)\b/.test(text)
              && !/=\s*await/.test(text)) {
            violations.push({ file: currentFile, line: newLineNo, rule: 'supabase-write-result-discarded', text: text.trim() })
          }
        }

        // Rule 9 — M12 phase 3: a NEW Ask Aria persona prompt that does not come from the rail.
        //
        // On 4 September an owner asked Ask Aria to "tidy up before the weekend" and was told to
        // make his bed. The lane that answered had written its own 639-character system prompt with
        // the business explicitly excluded, and nothing forced it to carry the constitution — which
        // at the time existed only as a template literal inside api/aria/ask/route.ts, importable
        // by nothing. Seven lanes can answer in Ask Aria; four had written their own partial
        // version of the same rules and one had none.
        //
        // A new `You are Aria` string in an Ask Aria path is that bug being reintroduced. Prompts
        // are assembled by assembleAriaPrompt (src/lib/aria/prompt/assemble.ts), which cannot omit
        // the constitution. Scoped to the Ask Aria paths deliberately: the other 88 persona strings
        // across 68 files are other surfaces, and migrating them is a separate sprint, not this
        // guard's job — the same grandfathering every rule above uses.
        // Test files are excluded: they SCAN and ASSERT prompts, they do not assemble one at
        // runtime, and the assertions that hold this very rule have to quote the phrase it blocks.
        // Caught by the rule firing on its own test file on the first push — precision, not a
        // loosening: no production path gains an exemption.
        if (/You are Aria/.test(text)
            && !/\.test\.tsx?$/.test(currentFile)
            && /^src\/(app\/api\/aria\/ask\/|lib\/aria\/(ask\/|prompt\/|council\.ts|slim-context\.ts))/.test(currentFile)
            && !ASK_ARIA_PROMPT_ALLOWLIST.includes(currentFile)) {
          violations.push({ file: currentFile, line: newLineNo, rule: 'ask-aria-prompt-outside-rail', text: text.trim() })
        }

        // Rule 7 — MS12 phase 6: a NEW write to a tombstoned UOM column. The object-key form
        // (`items_per_case: value`) is the write signature — payload objects for insert/update/
        // upsert. Reads (select strings) are untouched; type declarations in database.types.ts
        // are exempt above. Points at uom.ts, which records why each column is dead.
        if (/\b(items_per_case|case_quantity|cases_in_stock|sell_uom|cases_on_hand|cases_reorder_level|cases_reorder_amount|cases_reorder_limit|cases_max_on_hand)\s*:/.test(text)
            && !/^\s*(\/\/|\*|interface |type )/.test(text)
            && !UOM_TOMBSTONE_WRITE_ALLOWLIST.includes(currentFile)) {
          violations.push({ file: currentFile, line: newLineNo, rule: 'tombstoned-uom-write', text: text.trim() })
        }
      }

      const arr = addedLinesByFile.get(currentFile) ?? []
      arr.push({ line: newLineNo, text })
      addedLinesByFile.set(currentFile, arr)

      newLineNo++
    } else if (!raw.startsWith('-')) {
      newLineNo++
    }
  }

  // Rule 3 — ad-hoc revenue sum: both a total_amount reference AND a .reduce( call newly added
  // to the same file. Conservative on purpose (two independent signals, not one) to avoid flagging
  // a line that merely displays/reads total_amount without summing it.
  for (const [file, lines] of addedLinesByFile) {
    const hasTotalAmount = lines.some(l => /total_amount/.test(l.text))
    const reduceLine = lines.find(l => /\.reduce\(/.test(l.text))
    if (hasTotalAmount && reduceLine) {
      violations.push({ file, line: reduceLine.line, rule: 'ad-hoc-revenue-sum', text: reduceLine.text.trim() })
    }
  }

  // Rule 4 — SECURITY-P5: a migration creates a SECURITY DEFINER function but never REVOKEs
  // EXECUTE in the same file. Postgres grants EXECUTE to PUBLIC by default on function creation,
  // so "create, forget to revoke" ships wide open by default — this was the root cause of every
  // finding in SECURITY-P5. Two independent signals (CREATE FUNCTION...SECURITY DEFINER present,
  // REVOKE absent) in the same file's new lines, same conservative shape as rule 3.
  for (const [file, lines] of addedLinesByFile) {
    if (!file.endsWith('.sql')) continue
    const definerLine = lines.find(l => /security\s+definer/i.test(l.text))
    const hasRevoke = lines.some(l => /\brevoke\b/i.test(l.text))
    if (definerLine && !hasRevoke) {
      violations.push({ file, line: definerLine.line, rule: 'definer-function-missing-revoke', text: definerLine.text.trim() })
    }
  }

  return violations
}

function main() {
  let diff: string
  try {
    diff = getDiff()
  } catch (e) {
    console.error('[canon-rail-guard] failed to compute git diff:', (e as Error).message)
    process.exit(1)
  }

  const violations = scan(diff)

  if (violations.length === 0) {
    console.log('[canon-rail-guard] no new canonical-path violations introduced. Pass.')
    process.exit(0)
  }

  console.error(`[canon-rail-guard] ${violations.length} new violation(s) found — these are NEW lines only, pre-existing code is grandfathered:\n`)
  for (const v of violations) {
    console.error(`  ${v.file}:${v.line}  [${v.rule}]\n    ${v.text}\n`)
  }
  console.error('Fix: use withBusinessContext (src/lib/api/with-error-capture.ts) instead of a local getBid/getBusinessId/getBiz;')
  console.error('use .eq(\'status\',\'completed\') or getRevenueSnapshot()/getRevenueForRange() instead of neq(\'voided\')/a hand-rolled sum;')
  console.error('add REVOKE EXECUTE ... FROM PUBLIC, anon[, authenticated] in the same migration file as any new SECURITY DEFINER function;')
  console.error("call models through callModel() from src/lib/ai/gateway.ts — it is the only door. It requires a businessId,")
  console.error("so every call lands in aria_ai_calls; it classifies truncation on the shared rail; and it passes your model")
  console.error("through unchanged. 171 files construct their own client today and that list can only shrink;")
  console.error("READ THE ERROR: Supabase RESOLVES with { data, error } and never throws, so a discarded result is a")
  console.error("silent failure. Destructure `const { data, error } = await supabase...` and check it — log it at minimum.")
  console.error("A deliberate non-fatal write still logs: silence is never correct, non-fatal is. This is how")
  console.error("council-executor.ts got 0 audit inserts out of 854 and 95 councils marked complete having done nothing;")
  console.error("build Ask Aria system prompts with assembleAriaPrompt() from src/lib/aria/prompt/assemble.ts — it prepends the")
  console.error("constitution and cannot be told not to. A lane that wrote its own prompt is why an owner asking to 'tidy up before")
  console.error("the weekend' was told to make his bed on 4 Sep 2026;")
  console.error("send SMS with sendSMS() from src/lib/clicksend.ts (pass category: 'marketing' for anything promotional) rather than")
  console.error('calling rest.clicksend.com directly — the chokepoint is what checks sms_consent, honours the opt-out list, appends')
  console.error('the STOP notice and writes the sms_send_log audit row. A raw fetch does none of those and looks identical when sent;')
  console.error('get product costs from resolveCostFor/resolveCostBatch (src/lib/inventory/resolve-cost.ts) instead of selecting')
  console.error('cost_price directly — the raw column is a fabricated price*0.4 back-calculation on most rows, and only the resolver')
  console.error('ranks real transactions above it, reports unknown as null, and carries the provenance tier the UI shows;')
  console.error('never write items_per_case/case_quantity/cases_*/sell_uom — those columns are TOMBSTONED (see')
  console.error('src/lib/inventory/uom.ts): stock is BASE UNITS and the only live pack pair is purchase_uom + purchase_uom_qty.')
  console.error('Convert at the boundary with packConversion()/importPackFields(); refuse ambiguity, never default a factor;')
  console.error('route model calls through the gateway (src/lib/aria/model-router.ts) rather than instantiating a provider SDK')
  console.error('directly — the gateway is the one place that logs provider, model, tokens, latency, cost and outcome, and a')
  console.error('direct client logs whatever that call site remembered to log (93 production calls are recorded as $0 today).')
  process.exit(1)
}

main()
