import { Body, Container, Head, Heading, Html, Preview, Section, Text, Hr } from '@react-email/components';

interface Shift { date: string; start_hour: number; end_hour: number; outlet_name: string; }

interface RosterEmailProps {
  staffName: string;
  weekStart: string;
  shifts: Shift[];
  totalHours: number;
  businessName: string;
  businessContact: string;
}

function formatHour(h: number): string {
  const ampm = h >= 12 ? 'pm' : 'am';
  const h12 = h % 12 || 12;
  return `${h12}${ampm}`;
}

export function RosterPublishedEmail({ staffName, weekStart, shifts, totalHours, businessName, businessContact }: RosterEmailProps) {
  return (
    <Html>
      <Head />
      <Preview>Your roster for week of {weekStart} — {businessName}</Preview>
      <Body style={{ backgroundColor: '#f4f4f5', fontFamily: "'Manrope', sans-serif" }}>
        <Container style={{ maxWidth: 560, margin: '32px auto', backgroundColor: '#ffffff', borderRadius: 12, overflow: 'hidden' }}>
          <Section style={{ backgroundColor: '#08070D', padding: '24px 32px' }}>
            <Heading style={{ color: '#8B5CF6', fontSize: 22, fontWeight: 800, margin: 0 }}>Aria POS</Heading>
            <Text style={{ color: '#918AAE', margin: '4px 0 0', fontSize: 13 }}>Roster from {businessName}</Text>
          </Section>

          <Section style={{ padding: '28px 32px' }}>
            <Text style={{ color: '#111827', fontSize: 15 }}>Hi {staffName},</Text>
            <Text style={{ color: '#374151', fontSize: 15 }}>Your roster for the week of <strong>{weekStart}</strong> has been published.</Text>

            <Hr style={{ borderColor: '#e5e7eb', margin: '20px 0' }} />

            {shifts.length === 0 ? (
              <Text style={{ color: '#6b7280', fontSize: 13 }}>You have no shifts scheduled this week.</Text>
            ) : (
              shifts.map((shift, i) => (
                <Section key={i} style={{ backgroundColor: '#f9fafb', borderRadius: 8, padding: '12px 16px', marginBottom: 8 }}>
                  <Text style={{ margin: 0, fontSize: 14, fontWeight: 700, color: '#111827' }}>
                    {new Date(shift.date).toLocaleDateString('en-AU', { weekday: 'long', day: 'numeric', month: 'short' })}
                  </Text>
                  <Text style={{ margin: '2px 0 0', fontSize: 13, color: '#6b7280' }}>
                    {formatHour(shift.start_hour)} – {formatHour(shift.end_hour)} · {shift.outlet_name}
                  </Text>
                </Section>
              ))
            )}

            <Hr style={{ borderColor: '#e5e7eb', margin: '20px 0' }} />

            <Text style={{ color: '#374151', fontSize: 13 }}><strong>Total hours this week:</strong> {totalHours}h</Text>
            <Text style={{ color: '#6b7280', fontSize: 13 }}>Need to swap a shift? Contact {businessContact}.</Text>
          </Section>

          <Section style={{ backgroundColor: '#f9fafb', padding: '16px 32px' }}>
            <Text style={{ color: '#9ca3af', fontSize: 11, margin: 0 }}>Generated by Aria POS · ariaos.site</Text>
          </Section>
        </Container>
      </Body>
    </Html>
  );
}

export default RosterPublishedEmail;
