export const runtime = 'nodejs'
export const dynamic = 'force-dynamic'
export const maxDuration = 120

import sharp from 'sharp'
import { NextResponse } from 'next/server'
import { createClient } from '@supabase/supabase-js'
import { createServerSupabaseClient } from '@/lib/supabase-server'
import { getImageCreditStatus } from '@/lib/pos/auto-fetch-image'
import { withErrorCapture } from '@/lib/api/with-error-capture'

const BUCKET = 'pos-images'
const AI_GEN_COST = 0.04

function adminClient() {
  return createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!,
    { auth: { persistSession: false } },
  )
}

async function normalizeFromBuffer(buffer: Buffer): Promise<{ main: Buffer; thumb: Buffer }> {
  let quality = 85
  let mainBuf = await sharp(buffer)
    .resize(800, 800, { fit: 'inside', withoutEnlargement: true })
    .webp({ quality })
    .toBuffer()
  while (mainBuf.byteLength > 153600 && quality > 30) {
    quality -= 10
    mainBuf = await sharp(buffer)
      .resize(800, 800, { fit: 'inside', withoutEnlargement: true })
      .webp({ quality })
      .toBuffer()
  }
  const thumbBuf = await sharp(buffer)
    .resize(200, 200, { fit: 'inside', withoutEnlargement: true })
    .webp({ quality: 75 })
    .toBuffer()
  return { main: mainBuf, thumb: thumbBuf }
}

async function _POST(req: Request) {
  // ── 1. No-key check — nothing happens if misconfigured ───────────────────
  const openaiKey = process.env.OPENAI_API_KEY
  if (!openaiKey) {
    return NextResponse.json(
      { error: 'AI image generation is not configured on this account — you were not charged.', code: 'no_key' },
      { status: 503 },
    )
  }

  // ── 2. Auth ───────────────────────────────────────────────────────────────
  const supabase = createServerSupabaseClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  // ── 3. Body ───────────────────────────────────────────────────────────────
  const body = await req.json() as {
    productId?: string
    name: string
    description?: string
    categoryName?: string
    businessId: string
    // Client sends false (free path) or true (paid, confirmed by owner).
    // Absent = treat as false (free path attempted).
    confirmedPaid?: boolean
    // UUID generated by client per confirm action.
    // Prevents double-charge on network retry or double-submit.
    idempotencyKey?: string
  }
  if (!body.name?.trim()) return NextResponse.json({ error: 'Product name required' }, { status: 400 })
  if (!body.businessId) return NextResponse.json({ error: 'businessId required' }, { status: 400 })

  // ── 4. Verify business ownership ─────────────────────────────────────────
  const { data: biz } = await supabase
    .from('businesses')
    .select('id')
    .eq('id', body.businessId)
    .eq('user_id', user.id)
    .maybeSingle()
  if (!biz) return NextResponse.json({ error: 'Forbidden' }, { status: 403 })

  // ── 5. FREE-FIRST credit check (authoritative server-side decision) ───────
  // Client disclosure must match this. If the client thought it was free but
  // free_remaining is now 0, step 6 below surfaces the discrepancy.
  const sb = adminClient()
  const credits = await getImageCreditStatus(body.businessId)
  const isFree = credits.free_remaining > 0
  const hasPaid = credits.paid_credits > 0

  if (!isFree && !hasPaid) {
    return NextResponse.json({
      error: 'No image credits remaining. Purchase credits to generate AI images.',
      code: 'no_credits',
      credits,
    }, { status: 402 })
  }

  // ── 6. Paid path requires EXPLICIT owner confirmation ────────────────────
  // Free generations need no confirm (no charge to the owner).
  // Paid generations MUST carry confirmedPaid: true — set only after the owner
  // sees the price and clicks "Yes, charge $0.04" in the UI.
  // If the client thought it was free but server now says it's paid (race),
  // this gate triggers and the UI shows the paid confirm dialog before retry.
  if (!isFree && !body.confirmedPaid) {
    return NextResponse.json({
      error: 'This generation will use a paid credit ($' + AI_GEN_COST.toFixed(2) + '). Resend with confirmedPaid: true after owner approval.',
      requiresConfirm: true,
      cost: AI_GEN_COST,
      remaining_paid: credits.paid_credits,
      code: 'confirm_required',
    }, { status: 402 })
  }

  // ── 7. Idempotency pre-check (before any OpenAI call) ────────────────────
  // If this idempotencyKey was already processed, return success without
  // calling OpenAI or deducting credits again.
  if (body.idempotencyKey) {
    const { data: existingTxn } = await sb
      .from('pos_image_transactions')
      .select('id')
      .eq('idempotency_key', body.idempotencyKey)
      .maybeSingle()
    if (existingTxn) {
      return NextResponse.json(
        { already_processed: true, code: 'duplicate' },
        { status: 200 },
      )
    }
  }

  // ── 8. Generate via OpenAI — NO credit deducted yet ──────────────────────
  // If OpenAI fails for ANY reason the owner is NOT charged.
  let openAiImageUrl: string
  try {
    const { default: OpenAI } = await import('openai')
    const openai = new OpenAI({ apiKey: openaiKey })
    const categoryCtx = body.categoryName ? ' Category: ' + body.categoryName + '.' : ''
    const descCtx = body.description?.trim() ? ' ' + body.description.trim().slice(0, 120) + '.' : ''
    const prompt =
      'Professional product photograph: ' + body.name.trim() + '.' +
      categoryCtx + descCtx +
      ' Clean white background, studio lighting, sharp focus, centered, commercial product photography.'
    const genRes = await openai.images.generate({
      model: 'dall-e-3',
      prompt,
      n: 1,
      size: '1024x1024',
      quality: 'standard',
      response_format: 'url',
    })
    openAiImageUrl = genRes.data?.[0]?.url ?? ''
    if (!openAiImageUrl) throw new Error('OpenAI returned no image URL')
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err)
    return NextResponse.json(
      { error: 'Image generation failed — you were not charged. ' + msg, code: 'openai_failed' },
      { status: 502 },
    )
  }

  // ── 9. Download + normalize + upload — NO credit deducted yet ────────────
  // If download/upload fails for ANY reason the owner is NOT charged.
  let image_url: string
  let image_thumb_url: string | null
  try {
    const imgRes = await fetch(openAiImageUrl)
    if (!imgRes.ok) throw new Error('Failed to download generated image (' + imgRes.status + ')')
    const buffer = Buffer.from(await imgRes.arrayBuffer())
    const { main, thumb } = await normalizeFromBuffer(buffer)

    const ts = Date.now()
    const productId = body.productId
    const basePath = productId
      ? 'owner-products/' + productId + '-ai-' + ts
      : 'owner-products/ai-' + user.id.slice(0, 8) + '-' + ts

    const [mainUpload, thumbUpload] = await Promise.all([
      sb.storage.from(BUCKET).upload(basePath + '.webp', main, { contentType: 'image/webp', upsert: true }),
      sb.storage.from(BUCKET).upload(basePath + '-thumb.webp', thumb, { contentType: 'image/webp', upsert: true }),
    ])
    if (mainUpload.error) throw new Error(mainUpload.error.message)

    image_url = sb.storage.from(BUCKET).getPublicUrl(basePath + '.webp').data.publicUrl
    image_thumb_url = thumbUpload.error
      ? null
      : sb.storage.from(BUCKET).getPublicUrl(basePath + '-thumb.webp').data.publicUrl
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err)
    return NextResponse.json(
      { error: 'Image upload failed — you were not charged. ' + msg, code: 'upload_failed' },
      { status: 500 },
    )
  }

  // ── 10. SUCCESS PATH: log txn (idempotency gate) then deduct credit ───────
  // Generation + upload both succeeded. Now write the txn row first.
  // The unique index on idempotency_key means a concurrent duplicate request
  // will get a 23505 error here — we catch it and skip deduction.
  // Charge only succeeds if the insert does.
  const txnRow: Record<string, unknown> = {
    business_id: body.businessId,
    product_id: body.productId ?? null,
    // Honest type: 'free' when using the free quota, 'ai_generate' for paid.
    type: isFree ? 'free' : 'ai_generate',
    bg_removed: false,
    // Honest amount: 0 for free slot, actual cost for paid.
    amount_charged: isFree ? 0 : AI_GEN_COST,
    idempotency_key: body.idempotencyKey ?? null,
  }

  const { error: txnError } = await sb.from('pos_image_transactions').insert(txnRow)

  if (txnError?.code === '23505') {
    // Concurrent duplicate slipped through the pre-check — do NOT deduct credit.
    return NextResponse.json(
      { already_processed: true, image_url, image_thumb_url, code: 'duplicate_concurrent' },
      { status: 200 },
    )
  }
  if (txnError) {
    // Non-duplicate txn error: generation succeeded, log warning but still deduct.
    console.error('[generate-image] txn insert error (non-duplicate):', txnError.message)
  }

  // Deduct credit only after successful txn insert (or non-duplicate txn error).
  if (isFree) {
    await sb.rpc('increment_free_used', { bid: body.businessId })
  } else {
    await sb.rpc('decrement_paid_credit', { bid: body.businessId })
  }

  // ── 11. Update pos_products ───────────────────────────────────────────────
  // SECURITY-CRITICAL-3 — businessId was verified in step 4, but productId (a separate
  // client-supplied field) was never cross-checked against it before this admin-client write —
  // any authenticated user could overwrite another business's product image. The credit for this
  // generation has already been deducted against the caller's own verified businessId regardless
  // (steps 5-10), so a foreign productId only fails to attach, it can't be used to dodge payment.
  if (body.productId) {
    const { data: prod } = await sb.from('pos_products').select('id').eq('id', body.productId).eq('business_id', body.businessId).maybeSingle()
    if (!prod) {
      return NextResponse.json({
        error: 'Product not found for this business — image was generated but not attached.',
        image_url, image_thumb_url,
      }, { status: 404 })
    }
    await sb.from('pos_products').update({
      image_url,
      image_thumb_url,
      image_source: 'ai',
      updated_at: new Date().toISOString(),
    }).eq('id', body.productId).eq('business_id', body.businessId)
  }

  return NextResponse.json({
    image_url,
    image_thumb_url,
    was_free: isFree,
    remaining_free: isFree ? Math.max(0, credits.free_remaining - 1) : credits.free_remaining,
    remaining_paid: isFree ? credits.paid_credits : Math.max(0, credits.paid_credits - 1),
  })
}

export const POST = withErrorCapture('pos/products/generate-image', _POST)
