-- business_features: runtime-injected features generated by Aria
-- No code changes required — Aria generates a JSON config, FeatureRenderer renders it live

CREATE TABLE IF NOT EXISTS business_features (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  business_id     uuid REFERENCES businesses(id) ON DELETE CASCADE,
  name            text NOT NULL,
  description     text,
  feature_type    text NOT NULL, -- metric_card | leaderboard | tracker | calculator | data_table | alert_feed | quick_action | custom_report
  location        text NOT NULL DEFAULT 'dashboard', -- dashboard | pos | custom-features
  display_order   integer DEFAULT 0,
  config          jsonb NOT NULL DEFAULT '{}',
  is_active       boolean DEFAULT true,
  created_by      text DEFAULT 'aria',
  created_at      timestamptz DEFAULT now(),
  updated_at      timestamptz DEFAULT now()
);

ALTER TABLE business_features ENABLE ROW LEVEL SECURITY;

CREATE POLICY "own_business_features" ON business_features
  FOR ALL USING (
    business_id IN (SELECT id FROM businesses WHERE user_id = auth.uid())
  );

CREATE INDEX idx_business_features_business
  ON business_features(business_id, is_active, display_order);
