-- CX-1/P1 — Community member account link
-- Applied 2026-06-11 (manually applied to production DB — do NOT re-run)
--
-- ALTER TABLE community_members ADD COLUMN IF NOT EXISTS user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL;
-- CREATE INDEX IF NOT EXISTS idx_community_members_user_id ON community_members(user_id) WHERE user_id IS NOT NULL;
-- CREATE UNIQUE INDEX IF NOT EXISTS uq_community_members_user_id ON community_members(user_id) WHERE user_id IS NOT NULL;
