import { createServerSupabaseClient } from '@/lib/supabase-server'

type Supabase = ReturnType<typeof createServerSupabaseClient>

export interface ExecuteResult {
  ok: boolean
  message: string
  outcome?: Record<string, unknown>
}

async function executeReorder(
  supabase: Supabase,
  bid: string,
  decData: Record<string, unknown>,
): Promise<ExecuteResult> {
  const {
    supplier_id = null,
    supplier_name = 'Unknown Supplier',
    lines = [],
    total_cost = 0,
  } = decData as {
    supplier_id?: string | null
    supplier_name?: string
    lines?: Array<{ product_id: string; product_name: string; qty: number; unit_cost: number; total: number }>
    total_cost?: number
  }

  const poLines = Array.isArray(lines) ? lines : []
  const total = typeof total_cost === 'number' ? total_cost : 0

  // Create real pos_purchase_orders entry
  const { data: po, error: poError } = await supabase
    .from('pos_purchase_orders')
    .insert({
      business_id: bid,
      supplier_id: supplier_id ?? null,
      status: 'draft',
      subtotal: total,
      total,
      created_by: 'Aria Agent',
      source: 'agent',
      notes: `Auto-generated by Aria reorder agent${supplier_name ? ` for ${supplier_name}` : ''}`,
    })
    .select()
    .single()

  if (poError) {
    console.error('[agent-executor/reorder] PO insert error:', poError.message)
    return { ok: false, message: poError.message }
  }

  // Insert line items
  if (poLines.length > 0) {
    const items = poLines.map(l => ({
      order_id: po.id,
      product_id: l.product_id,
      product_name: l.product_name,
      quantity_ordered: l.qty,
      quantity_received: 0,
      unit_cost: l.unit_cost,
      line_total: l.qty * l.unit_cost,
    }))
    const { error: itemsError } = await supabase.from('pos_purchase_order_items').insert(items)
    if (itemsError) {
      console.error('[agent-executor/reorder] items insert error:', itemsError.message)
    }
  }

  // Also update any matching purchase_order_drafts to approved
  await supabase
    .from('purchase_order_drafts')
    .update({ status: 'approved' })
    .eq('business_id', bid)
    .eq('draft_type', 'agent_reorder')
    .eq('status', 'pending_approval')

  return {
    ok: true,
    message: `Purchase order created: ${poLines.length} lines, A$${total.toFixed(2)}`,
    outcome: { po_id: po.id, line_count: poLines.length, total },
  }
}

async function executePricing(
  supabase: Supabase,
  bid: string,
  decData: Record<string, unknown>,
): Promise<ExecuteResult> {
  const { product_id, suggested_price, current_price } = decData as {
    product_id: string
    suggested_price: number
    current_price?: number
  }

  const tomorrow = new Date(Date.now() + 86400000).toISOString().split('T')[0]
  const { error } = await supabase.from('pos_future_prices').insert({
    business_id: bid,
    product_id,
    new_price: suggested_price,
    effective_date: tomorrow,
    current_price: current_price ?? null,
    applied: false,
  })

  if (error) {
    console.error('[agent-executor/pricing] pos_future_prices insert error:', error.message)
    return { ok: false, message: error.message }
  }
  return {
    ok: true,
    message: `Price change to A$${suggested_price} scheduled for ${tomorrow}`,
    outcome: { product_id, new_price: suggested_price, effective_date: tomorrow },
  }
}

async function executeSchedule(
  supabase: Supabase,
  bid: string,
  decData: Record<string, unknown>,
): Promise<ExecuteResult> {
  const { outlet_id, week_start } = decData as {
    outlet_id: string
    week_start: string
  }

  await supabase
    .from('pos_rosters')
    .update({ published: true, published_at: new Date().toISOString() })
    .eq('business_id', bid)
    .eq('outlet_id', outlet_id)
    .eq('week_start', week_start)

  return {
    ok: true,
    message: `Roster for week of ${week_start} published`,
    outcome: { outlet_id, week_start },
  }
}

export async function executeApprovedDecision(
  decisionId: string,
  supabase: Supabase,
): Promise<ExecuteResult> {
  const { data: decision, error } = await supabase
    .from('agent_decisions')
    .select('*')
    .eq('id', decisionId)
    .single()

  if (error || !decision) {
    return { ok: false, message: `Decision not found: ${error?.message ?? decisionId}` }
  }

  const bid = decision.business_id as string
  const decData = (decision.decision_data ?? {}) as Record<string, unknown>

  let result: ExecuteResult
  switch (decision.agent_type as string) {
    case 'reorder':
      result = await executeReorder(supabase, bid, decData)
      break
    case 'pricing':
      result = await executePricing(supabase, bid, decData)
      break
    case 'schedule':
      result = await executeSchedule(supabase, bid, decData)
      break
    default:
      result = { ok: false, message: `Unknown agent type: ${decision.agent_type}` }
  }

  await supabase
    .from('agent_decisions')
    .update({
      status: result.ok ? 'approved' : 'failed',
      executed_at: result.ok ? new Date().toISOString() : null,
      outcome: result.outcome ?? { message: result.message },
    })
    .eq('id', decisionId)

  return result
}