// Auto-generated by scripts/generate-dalle-cafe-images.ts
// 58 professional product photos generated by gpt-image-1, stored in Supabase Storage.
// Isolated on white background, photorealistic. Permanent CDN URLs — never expire.

const BASE = 'https://nxfzippunqvqsvkmwtjv.supabase.co/storage/v1/object/public/pos-images/cafe-dalle'

export const CAFE_IMAGE_MAP: Record<string, string> = {
  'espresso':         `${BASE}/espresso.png`,
  'flat-white':       `${BASE}/flat-white.png`,
  'latte':            `${BASE}/latte.png`,
  'cappuccino':       `${BASE}/cappuccino.png`,
  'long-black':       `${BASE}/long-black.png`,
  'macchiato':        `${BASE}/macchiato.png`,
  'mocha':            `${BASE}/mocha.png`,
  'piccolo':          `${BASE}/piccolo.png`,
  'cortado':          `${BASE}/cortado.png`,
  'cold-brew':        `${BASE}/cold-brew.png`,
  'iced-latte':       `${BASE}/iced-latte.png`,
  'iced-mocha':       `${BASE}/iced-mocha.png`,
  'iced-chocolate':   `${BASE}/iced-chocolate.png`,
  'affogato':         `${BASE}/affogato.png`,
  'frappe':           `${BASE}/frappe.png`,
  'tea':              `${BASE}/tea.png`,
  'chai-latte':       `${BASE}/chai-latte.png`,
  'matcha-latte':     `${BASE}/matcha-latte.png`,
  'turmeric-latte':   `${BASE}/turmeric-latte.png`,
  'dirty-chai':       `${BASE}/dirty-chai.png`,
  'hot-chocolate':    `${BASE}/hot-chocolate.png`,
  'orange-juice':     `${BASE}/orange-juice.png`,
  'apple-juice':      `${BASE}/apple-juice.png`,
  'sparkling-water':  `${BASE}/sparkling-water.png`,
  'water-bottle':     `${BASE}/water-bottle.png`,
  'banana-smoothie':  `${BASE}/banana-smoothie.png`,
  'berry-smoothie':   `${BASE}/berry-smoothie.png`,
  'mango-smoothie':   `${BASE}/mango-smoothie.png`,
  'green-smoothie':   `${BASE}/green-smoothie.png`,
  'milkshake':        `${BASE}/milkshake.png`,
  'soft-drink':       `${BASE}/soft-drink.png`,
  'avocado-toast':    `${BASE}/avocado-toast.png`,
  'eggs-benedict':    `${BASE}/eggs-benedict.png`,
  'scrambled-eggs':   `${BASE}/scrambled-eggs.png`,
  'poached-eggs':     `${BASE}/poached-eggs.png`,
  'big-breakfast':    `${BASE}/big-breakfast.png`,
  'bacon-egg-roll':   `${BASE}/bacon-egg-roll.png`,
  'granola-bowl':     `${BASE}/granola-bowl.png`,
  'acai-bowl':        `${BASE}/acai-bowl.png`,
  'banana-bread':     `${BASE}/banana-bread.png`,
  'bircher-muesli':   `${BASE}/bircher-muesli.png`,
  'toasted-sandwich': `${BASE}/toasted-sandwich.png`,
  'beef-burger':      `${BASE}/beef-burger.png`,
  'chicken-wrap':     `${BASE}/chicken-wrap.png`,
  'falafel-wrap':     `${BASE}/falafel-wrap.png`,
  'caesar-salad':     `${BASE}/caesar-salad.png`,
  'greek-salad':      `${BASE}/greek-salad.png`,
  'soup':             `${BASE}/soup.png`,
  'quiche':           `${BASE}/quiche.png`,
  'sausage-roll':     `${BASE}/sausage-roll.png`,
  'meat-pie':         `${BASE}/meat-pie.png`,
  'croissant':        `${BASE}/croissant.png`,
  'pain-au-chocolat': `${BASE}/pain-au-chocolat.png`,
  'muffin':           `${BASE}/muffin.png`,
  'cookie':           `${BASE}/cookie.png`,
  'brownie':          `${BASE}/brownie.png`,
  'cake-slice':       `${BASE}/cake-slice.png`,
  'scone':            `${BASE}/scone.png`,
}

export function getCafeImageKey(productName: string): string {
  const name = productName.toLowerCase()
  if (name.includes('flat white')) return 'flat-white'
  if (name.includes('iced latte')) return 'iced-latte'
  if (name.includes('iced mocha')) return 'iced-mocha'
  if (name.includes('iced chocolate')) return 'iced-chocolate'
  if (name.includes('iced long black') || name.includes('cold brew')) return 'cold-brew'
  if (name.includes('cappuccino')) return 'cappuccino'
  if (name.includes('matcha')) return 'matcha-latte'
  if (name.includes('dirty chai')) return 'dirty-chai'
  if (name.includes('chai latte')) return 'chai-latte'
  if (name.includes('turmeric')) return 'turmeric-latte'
  if (name.includes('frappé') || name.includes('frappe')) return 'frappe'
  if (name.includes('affogato')) return 'affogato'
  if (name.includes('piccolo')) return 'piccolo'
  if (name.includes('cortado')) return 'cortado'
  if (name.includes('macchiato')) return 'macchiato'
  if (name.includes('long black')) return 'long-black'
  if (name.includes('mocha')) return 'mocha'
  if (name.includes('hot chocolate')) return 'hot-chocolate'
  if (name.includes('latte')) return 'latte'
  if (name.includes('espresso') || name.includes('short black')) return 'espresso'
  if (name.includes('english breakfast') || name.includes('earl grey') ||
      name.includes('green sencha') || name.includes('peppermint') ||
      name.includes('chamomile') || name.includes('chai tea') ||
      name.includes('lemongrass')) return 'tea'
  if (name.includes('orange juice')) return 'orange-juice'
  if (name.includes('apple juice')) return 'apple-juice'
  if (name.includes('sparkling water')) return 'sparkling-water'
  if (name.includes('still water')) return 'water-bottle'
  if (name.includes('banana smoothie')) return 'banana-smoothie'
  if (name.includes('berry smoothie') || name.includes('acai smoothie')) return 'berry-smoothie'
  if (name.includes('mango smoothie')) return 'mango-smoothie'
  if (name.includes('green smoothie')) return 'green-smoothie'
  if (name.includes('milkshake')) return 'milkshake'
  if (name.includes('soft drink')) return 'soft-drink'
  if (name.includes('avocado toast')) return 'avocado-toast'
  if (name.includes('eggs benedict')) return 'eggs-benedict'
  if (name.includes('scrambled eggs')) return 'scrambled-eggs'
  if (name.includes('poached eggs')) return 'poached-eggs'
  if (name.includes('big breakfast')) return 'big-breakfast'
  if (name.includes('bacon and egg roll')) return 'bacon-egg-roll'
  if (name.includes('granola bowl')) return 'granola-bowl'
  if (name.includes('acai bowl')) return 'acai-bowl'
  if (name.includes('banana bread')) return 'banana-bread'
  if (name.includes('bircher muesli')) return 'bircher-muesli'
  if (name.includes('toasted sandwich')) return 'toasted-sandwich'
  if (name.includes('beef burger')) return 'beef-burger'
  if (name.includes('chicken wrap')) return 'chicken-wrap'
  if (name.includes('falafel wrap')) return 'falafel-wrap'
  if (name.includes('caesar salad')) return 'caesar-salad'
  if (name.includes('greek salad')) return 'greek-salad'
  if (name.includes('soup')) return 'soup'
  if (name.includes('quiche')) return 'quiche'
  if (name.includes('sausage roll')) return 'sausage-roll'
  if (name.includes('meat pie')) return 'meat-pie'
  if (name.includes('pain au chocolat')) return 'pain-au-chocolat'
  if (name.includes('croissant')) return 'croissant'
  if (name.includes('muffin')) return 'muffin'
  if (name.includes('cookie')) return 'cookie'
  if (name.includes('brownie')) return 'brownie'
  if (name.includes('cake') || name.includes('slice')) return 'cake-slice'
  if (name.includes('scone')) return 'scone'
  return 'espresso'
}

export function getCafeProductImage(productName: string): string {
  return CAFE_IMAGE_MAP[getCafeImageKey(productName)] ?? CAFE_IMAGE_MAP['espresso']
}